---
- name: Provision OS + PSMDB on all replica set nodes
  hosts: replicaset:arbiter:extra_replicaset
  become: true
  roles:
    - common
    - psmdb

- name: Initiate the replica set and create the admin user
  hosts: replicaset
  become: true
  roles:
    - replicaset
